packages:
  - 'packages/*'
  - 'indexer'
  - 'backend'
  - 'frontend'
  - 'mobile'
allowBuilds:
  '@firebase/util': true
  core-js: true
  esbuild: true
  msw: true
  protobufjs: true
  unrs-resolver: true
